# Generated by Django 4.2.3 on 2023-08-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentId',
        ),
    ]
