# Generated by Django 4.2.3 on 2023-08-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_delete_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sReg', models.IntegerField(default=0)),
            ],
        ),
    ]
