# Generated by Django 4.2.3 on 2023-08-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_studentreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studid', to='receipe.studentreg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='sReg',
            field=models.IntegerField(default=111),
        ),
    ]
