# Generated by Django 4.2.3 on 2023-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0004_student_studentid_alter_studentreg_sreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='sReg',
            field=models.CharField(max_length=20),
        ),
    ]
