# Generated by Django 4.2.3 on 2023-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0005_alter_studentreg_sreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(max_length=50),
        ),
    ]
