# Generated by Django 4.2.3 on 2023-08-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0006_alter_student_studentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='receipe.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='receipe.studentreg'),
        ),
    ]
