# Generated by Django 4.2.3 on 2023-08-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0008_subject_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(auto_created=True)),
                ('Rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentresult', to='receipe.student')),
            ],
        ),
    ]
