# Generated by Django 4.2.3 on 2023-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0009_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='date_of_report',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentreport',
            unique_together={('student', 'Rank')},
        ),
    ]
